// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receita.Domain.Infrastructure.Context;

namespace Receita.Domain.Migrations
{
    [DbContext(typeof(ReceitaContext))]
    [Migration("20191009232537_AlterarTabelaFoto")]
    partial class AlterarTabelaFoto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Receita.Domain.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo")
                        .HasColumnName("Titulo")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("Pk_Categoria_Id");

                    b.ToTable("tbCategoria");
                });

            modelBuilder.Entity("Receita.Domain.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("Pk_Grupo_Id");

                    b.ToTable("tbGrupo");
                });

            modelBuilder.Entity("Receita.Domain.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(400);

                    b.Property<string>("Foto")
                        .HasColumnName("Foto")
                        .HasMaxLength(50);

                    b.Property<int>("IdCategoria")
                        .HasColumnName("IdCategoria")
                        .HasMaxLength(400);

                    b.Property<int>("IdUsuario")
                        .HasColumnName("IdUsuario")
                        .HasMaxLength(20);

                    b.Property<string>("Ingredientes")
                        .HasColumnName("Ingredientes")
                        .HasMaxLength(400);

                    b.Property<string>("ModoDePreparo")
                        .HasColumnName("ModoDePreparo")
                        .HasMaxLength(400);

                    b.Property<bool>("Status")
                        .HasColumnName("Status")
                        .HasMaxLength(10);

                    b.Property<string>("Tag")
                        .HasColumnName("Tag")
                        .HasMaxLength(10);

                    b.Property<string>("Titulo")
                        .HasColumnName("TituloReceita")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasName("Pk_Receita_Id");

                    b.ToTable("tbReceita");
                });

            modelBuilder.Entity("Receita.Domain.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(10);

                    b.HasKey("Id")
                        .HasName("Pk_Status_Id");

                    b.ToTable("tbStatus");
                });

            modelBuilder.Entity("Receita.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(50);

                    b.Property<int>("IdGrupo")
                        .HasColumnName("IdGrupo")
                        .HasMaxLength(10);

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("Pk_Usuario_Id");

                    b.ToTable("tbUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
