// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Receita.Domain.Context;

namespace Receita.Domain.Migrations
{
    [DbContext(typeof(ReceitaContext))]
    partial class ReceitaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Receita")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Receita.Domain.Model.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdCategoria")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo")
                        .HasColumnName("Titulo")
                        .HasMaxLength(50);

                    b.HasKey("IdCategoria")
                        .HasName("IdCategoria");

                    b.ToTable("tbCategoria");
                });

            modelBuilder.Entity("Receita.Domain.Model.Papel", b =>
                {
                    b.Property<int>("IdPapel")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdPapel")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc_papel")
                        .HasColumnName("Desc_Papel")
                        .HasMaxLength(50);

                    b.HasKey("IdPapel")
                        .HasName("IdPapel");

                    b.ToTable("tbPapel");
                });

            modelBuilder.Entity("Receita.Domain.Model.Receita", b =>
                {
                    b.Property<int>("idReceita")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idReceita")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(400);

                    b.Property<string>("Foto")
                        .HasColumnName("Foto")
                        .HasMaxLength(50);

                    b.Property<int>("IdCategoria")
                        .HasColumnName("IdCategoria")
                        .HasMaxLength(400);

                    b.Property<int>("IdUsuario")
                        .HasColumnName("IdUsuario")
                        .HasMaxLength(20);

                    b.Property<string>("Ingredientes")
                        .HasColumnName("Ingredientes")
                        .HasMaxLength(400);

                    b.Property<string>("ModoDePreparo")
                        .HasColumnName("ModoDePreparo")
                        .HasMaxLength(400);

                    b.Property<bool>("Status")
                        .HasColumnName("Status")
                        .HasMaxLength(10);

                    b.Property<string>("Tag")
                        .HasColumnName("Tag")
                        .HasMaxLength(10);

                    b.Property<string>("TituloReceita")
                        .HasColumnName("TituloReceita")
                        .HasMaxLength(50);

                    b.HasKey("idReceita")
                        .HasName("IdReceita");

                    b.ToTable("TbReceita");
                });

            modelBuilder.Entity("Receita.Domain.Model.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdStatus")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc_Status")
                        .HasColumnName("Desc_Status")
                        .HasMaxLength(10);

                    b.HasKey("IdStatus")
                        .HasName("IdStatus");

                    b.ToTable("TbStatus");
                });

            modelBuilder.Entity("Receita.Domain.Model.UsuarioAdm", b =>
                {
                    b.Property<int>("IdUsuarioAdm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdUsuarioAdm")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(50);

                    b.Property<int>("IdPapel")
                        .HasColumnName("IdPapel")
                        .HasMaxLength(10);

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasMaxLength(20);

                    b.Property<int?>("statusIdStatus");

                    b.HasKey("IdUsuarioAdm")
                        .HasName("IdUsuarioAdm");

                    b.HasIndex("statusIdStatus");

                    b.ToTable("TbUsuariAdm");
                });

            modelBuilder.Entity("Receita.Domain.Model.UsuarioAdm", b =>
                {
                    b.HasOne("Receita.Domain.Model.Status", "status")
                        .WithMany()
                        .HasForeignKey("statusIdStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
